### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by kodeine** [maciejtreder/angular-universal-pwa#42]
Hello,
So i have an existing app which has universal. I installed serverless and also added additional packages in package.json.

package.json
```
"dependencies": {
    "aws-serverless-express": "3.0.0"
},
"devDependencies": {
    "serverless": "^1.21.1",
    "serverless-apigw-binary": "^0.4.0"
}
```

I copied `lambda.js` and `serverless.yml` to the root of the directory.

Is this all needed to deploy? because when i run `serverless deploy`, it deploys but when i goto the url i get 
```
{
message: "Internal server error"
}
```

**Comment by maciejtreder** [comment]
Hello,

As far as I understand you are not using this repository as a backbone, but trying to pick up few elements and combine them with some existing code.

There could be multiple reasons of such error. The first one could be that your universal app is exposed in different catalog/filename. As you can see in `lambda.js` it is requesting file from this location:
const app = require('././dist/server');

Another problem could be, how your serverside script is ended. Take a look at:
https://github.com/maciejtreder/angular-universal-pwa/blob/master/src/main.server.aot.ts
You won't find there lines responsible for launching express (this action is delegated to awsServerlessExpress). Those are moved to the `local.js`:

```
let app = require('./dist/server.js');
let port = process.env.PORT || 8000;

// Server
 app.listen(port, () => {
    console.log(`Listening on: http://localhost:${port}`);
});
```

If you want to report bugs to this repository, you should use it as a backbone and move your application code to it, not otherwise (what I strongly recommend). Right now, this is help request **not relayed to this boilerplate** and better place for such questions is stackoverflow (where you can find much more people, often able to help you immediately).

**Comment by meanMonk** [comment]
Hi,

I have followed the proper documentation from github for ng-toolkit/universal and also install serverless in project.

For the very first time when I deploy the code to aws it works perfect.
Now I am trying to deploy new version with same command
```npm run build:serverless:deploy``` 
Process getting completed but I am seeing the same internal server error.

https://t1s9xckxlf.execute-api.eu-central-1.amazonaws.com/production
Can someone please help me out with this?

**Comment by AbuHani** [comment]
> Hi,
> 
> I have followed the proper documentation from github for ng-toolkit/universal and also install serverless in project.
> 
> For the very first time when I deploy the code to aws it works perfect.
> Now I am trying to deploy new version with same command
> `npm run build:serverless:deploy`
> Process getting completed but I am seeing the same internal server error.
> 
> https://t1s9xckxlf.execute-api.eu-central-1.amazonaws.com/production
> Can someone please help me out with this?

i have same issue did you solve it ?
