### ISSUE TITLE
Prod Server Build

### ISSUE THREAD

**Issue by bennykelly** [maciejtreder/angular-universal-pwa#99]
When I run the `npm run server` command and load `http://localhost:8080` I'm redirected to https://www.angular-universal-pwa.maciejtreder.com/

I checked the `main.server.js` file and updated the `app.get('/**', (req, res) => {..... ` command, however, on a fresh build, still getting redirected? 

Local updates therefore not getting reflected. Anything obvious I;m missing?

Thanks in advance...

**Comment by diegolameira** [comment]
That's because it was a 301 permanent redirect, to solve this you need to access devtools and clear browser cache with a right button mouse click over the first request localhost:8080 on networks devtools tab.

I couldn't figure out the need of this redirect, maybe if this is some special need then it might not be hardcoded as it is. If the author (@maciejtreder) clarify us we could just remove or even make a PR with the fix for passing it as configuration somehow.

**Comment by maciejtreder** [comment]
@diegolameira @bennykelly Purpose of this redirect is for production build of the demo (which is using this repository for build). Feel free to make changes in the code and place PR!

We could definitely change conditional to `if(req.url.contains(angular-universal-pwa.maciejtreder.com) ^^ req.url !== ‘https://www....) {//do 301 here}`

@bennykelly As @diegolameira wrote, after clearing cache etc, you should no longer be redirected to the demo page.
